import type { AnimFieldDef } from './Animation.types'

export const BASIC_FIELDS = [
  {
    label: 'Move X',
    animKey: 'x',
    durationKey: 'xDuration',
    tooltip: 'Horizontal movement in pixels',
    advancedTooltip: 'Comma-separated keyframes for horizontal movement (e.g. 0, 10, 0)',
    defaultValue: 0,
    min: -200,
    max: 200,
    step: 1,
    placeholder: '0, 10, 0',
  },
  {
    label: 'Move Y',
    animKey: 'y',
    durationKey: 'yDuration',
    tooltip: 'Vertical movement in pixels',
    advancedTooltip: 'Comma-separated keyframes for vertical movement (e.g. 0, -20, 0)',
    defaultValue: 0,
    min: -200,
    max: 200,
    step: 1,
    placeholder: '0, -20, 0',
  },
  {
    label: 'Scale',
    animKey: 'scale',
    durationKey: 'scaleDuration',
    tooltip: 'Size multiplier (1 = original size)',
    advancedTooltip: 'Comma-separated keyframes for scale (e.g. 1, 1.5, 1)',
    defaultValue: 1,
    min: 0,
    max: 3,
    step: 0.1,
    placeholder: '1, 1.5, 1',
  },
  {
    label: 'Rotate',
    animKey: 'rotate',
    durationKey: 'rotateDuration',
    tooltip: 'Rotation angle in degrees',
    advancedTooltip: 'Comma-separated keyframes for rotation in degrees (e.g. 0, 360)',
    defaultValue: 0,
    min: -360,
    max: 360,
    step: 1,
    placeholder: '0, 360',
  },
  {
    label: 'Opacity',
    animKey: 'opacity',
    durationKey: 'opacityDuration',
    tooltip: 'Animated transparency (0 = invisible, 1 = visible)',
    advancedTooltip: 'Comma-separated keyframes for opacity (e.g. 0, 1, 0)',
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.1,
    placeholder: '0, 1, 0',
  },
] as const satisfies readonly AnimFieldDef[]

export const ADVANCED_3D_FIELDS = [
  {
    label: 'Rotate X (3D)',
    animKey: 'rotateX',
    durationKey: 'rotateXDuration',
    tooltip: '3D rotation around the horizontal axis',
    advancedTooltip: 'Comma-separated keyframes for 3D X rotation (e.g. 0, 180, 0)',
    defaultValue: 0,
    min: -360,
    max: 360,
    step: 1,
    placeholder: '0, 180, 0',
  },
  {
    label: 'Rotate Y (3D)',
    animKey: 'rotateY',
    durationKey: 'rotateYDuration',
    tooltip: '3D rotation around the vertical axis',
    advancedTooltip: 'Comma-separated keyframes for 3D Y rotation (e.g. 0, 180, 0)',
    defaultValue: 0,
    min: -360,
    max: 360,
    step: 1,
    placeholder: '0, 180, 0',
  },
  {
    label: 'Skew X',
    animKey: 'skewX',
    durationKey: 'skewXDuration',
    tooltip: 'Horizontal slant distortion in degrees',
    advancedTooltip: 'Comma-separated keyframes for horizontal skew (e.g. 0, 20, 0)',
    defaultValue: 0,
    min: -90,
    max: 90,
    step: 1,
    placeholder: '0, 20, 0',
  },
  {
    label: 'Skew Y',
    animKey: 'skewY',
    durationKey: 'skewYDuration',
    tooltip: 'Vertical slant distortion in degrees',
    advancedTooltip: 'Comma-separated keyframes for vertical skew (e.g. 0, 20, 0)',
    defaultValue: 0,
    min: -90,
    max: 90,
    step: 1,
    placeholder: '0, 20, 0',
  },
] as const satisfies readonly AnimFieldDef[]

export const PATH_FIELDS = [
  {
    label: 'Draw Path',
    animKey: 'pathLength',
    durationKey: 'pathLengthDuration',
    tooltip: 'Animate stroke drawing (0 to 1 reveals the path)',
    advancedTooltip: 'Comma-separated keyframes for path drawing (e.g. 0, 1)',
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.01,
    placeholder: '0, 1',
  },
] as const satisfies readonly AnimFieldDef[]
