export const SAMPLE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <circle cx="12" cy="12" r="10"></circle>
  <path d="M12 8v8"></path>
  <path d="M8 12h8"></path>
</svg>`

export const VISUAL_TAGS = new Set([
  'svg',
  'g',
  'path',
  'rect',
  'circle',
  'ellipse',
  'line',
  'polyline',
  'polygon',
  'text',
  'tspan',
  'image',
  'use',
  'foreignobject',
])

export const PATH_DRAWABLE_TAGS = new Set([
  'path',
  'line',
  'polyline',
  'polygon',
  'circle',
  'ellipse',
  'rect',
])

export const STRUCTURAL_TAGS = new Set([
  'style',
  'defs',
  'clippath',
  'mask',
  'lineargradient',
  'radialgradient',
  'filter',
  'pattern',
  'symbol',
  'metadata',
  'title',
  'desc',
  'stop',
  'fegaussianblur',
  'feoffset',
  'feblend',
  'fecolormatrix',
  'fecomponenttransfer',
  'fecomposite',
  'feconvolvematrix',
  'fediffuselighting',
  'fedisplacementmap',
  'feflood',
  'feimage',
  'femerge',
  'femergenode',
  'femorphology',
  'fespecularlighting',
  'fetile',
  'feturbulence',
  'fefuncr',
  'fefuncg',
  'fefuncb',
  'fefunca',
  'fedistantlight',
  'fepointlight',
  'fespotlight',
])

export const reactPropsMap: Record<string, string> = {
  class: 'className',
  viewbox: 'viewBox',
  preserveaspectratio: 'preserveAspectRatio',
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-miterlimit': 'strokeMiterlimit',
  'stroke-dasharray': 'strokeDasharray',
  'stroke-dashoffset': 'strokeDashoffset',
  'fill-opacity': 'fillOpacity',
  'stroke-opacity': 'strokeOpacity',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
  'font-family': 'fontFamily',
  'font-size': 'fontSize',
  'font-weight': 'fontWeight',
  'text-anchor': 'textAnchor',
}
